#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 31 14:07:23 2020

@author: roncavallo
"""

This tool is a command line tool to be used with Python 2.7

This script is run at the command line and includes prompts to the user.

Anwser the prompts properly, there is little error handling in the script.

The script is capable of enermerating cities and users, and of creating a user as of this commit V2.


