#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 31 14:07:23 2020

@author: roncavallo
"""

This tool is a command line tool to be used with Python 2.7

When called from the command line